name: Python build

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install virtualenv
        run: |
          sudo apt update
          sudo apt install python3-pip
          python -m pip install virtualenv

      - name: Cache Python virtual environment
        id: pip-cache
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: ${{ runner.os }}-pip-cache-${{ hashFiles('./requirements*.txt') }}

      - name: Install Python requirements
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: |
          virtualenv ./.venv
          source ./.venv/bin/activate
          pip install -r ./requirements.txt -r ./requirements-code-style.txt


  code-style:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Python virtual environment
        id: pip-cache
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: ${{ runner.os }}-pip-cache-${{ hashFiles('./requirements*.txt') }}

      - name: Run python static code analyzers
        run: |
          source ./.venv/bin/activate
          flake8 . --count --statistics --config ./.flake8
          
      - name: Run Black
        uses: psf/black@stable
        with:
          options: "-S --line-length 120 --target-version py38 --check --diff --color"

  test:
    needs: code-style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install anderson
        run: pip install .
        
      - name: Check anderson is working
        run: anderson "python3 ./examples/python_bot/main.py" ./examples/python_bot/out/ ./examples/python_bot/config.yaml --debug
      
      - uses: actions/upload-artifact@v3
        with:
          name: python-bot-gifs
          path: ./examples/python_bot/out/
